version: "3.9"
services:

  # External system postgresql tpc-h database
  postgres-tpch:
    hostname: postgres-tpch
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
  pgadmin:
    image: dpage/pgadmin4:8.14
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 1
      PGPASSWORD: 1
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 80:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json      
    depends_on:
      - postgres-tpch

